/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDiagnosticsRouteImport } from './routes/_app/diagnostics'
import { Route as AppDownloadsRouteImport } from './routes/_app/downloads'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as PlayRatingKeyRouteImport } from './routes/play.$ratingKey'
import { Route as AppItemRatingKeyRouteImport } from './routes/_app/item.$ratingKey'
import { Route as AppLibraryLibraryIdRouteImport } from './routes/_app/library.$libraryId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticsRoute = AppDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const PlayRatingKeyRoute = PlayRatingKeyRouteImport.update({
  id: '/play/$ratingKey',
  path: '/play/$ratingKey',
  getParentRoute: () => rootRouteImport,
} as any)
const AppItemRatingKeyRoute = AppItemRatingKeyRouteImport.update({
  id: '/item/$ratingKey',
  path: '/item/$ratingKey',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryLibraryIdRoute = AppLibraryLibraryIdRouteImport.update({
  id: '/library/$libraryId',
  path: '/library/$libraryId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/diagnostics': typeof AppDiagnosticsRoute
  '/downloads': typeof AppDownloadsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/play/$ratingKey': typeof PlayRatingKeyRoute
  '/item/$ratingKey': typeof AppItemRatingKeyRoute
  '/library/$libraryId': typeof AppLibraryLibraryIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/diagnostics': typeof AppDiagnosticsRoute
  '/downloads': typeof AppDownloadsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/play/$ratingKey': typeof PlayRatingKeyRoute
  '/': typeof AppIndexRoute
  '/item/$ratingKey': typeof AppItemRatingKeyRoute
  '/library/$libraryId': typeof AppLibraryLibraryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/_app/diagnostics': typeof AppDiagnosticsRoute
  '/_app/downloads': typeof AppDownloadsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/play/$ratingKey': typeof PlayRatingKeyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/item/$ratingKey': typeof AppItemRatingKeyRoute
  '/_app/library/$libraryId': typeof AppLibraryLibraryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/servers'
    | '/diagnostics'
    | '/downloads'
    | '/search'
    | '/settings'
    | '/play/$ratingKey'
    | '/item/$ratingKey'
    | '/library/$libraryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/servers'
    | '/diagnostics'
    | '/downloads'
    | '/search'
    | '/settings'
    | '/play/$ratingKey'
    | '/'
    | '/item/$ratingKey'
    | '/library/$libraryId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/servers'
    | '/_app/diagnostics'
    | '/_app/downloads'
    | '/_app/search'
    | '/_app/settings'
    | '/play/$ratingKey'
    | '/_app/'
    | '/_app/item/$ratingKey'
    | '/_app/library/$libraryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ServersRoute: typeof ServersRoute
  PlayRatingKeyRoute: typeof PlayRatingKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnostics': {
      id: '/_app/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AppDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/play/$ratingKey': {
      id: '/play/$ratingKey'
      path: '/play/$ratingKey'
      fullPath: '/play/$ratingKey'
      preLoaderRoute: typeof PlayRatingKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/item/$ratingKey': {
      id: '/_app/item/$ratingKey'
      path: '/item/$ratingKey'
      fullPath: '/item/$ratingKey'
      preLoaderRoute: typeof AppItemRatingKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$libraryId': {
      id: '/_app/library/$libraryId'
      path: '/library/$libraryId'
      fullPath: '/library/$libraryId'
      preLoaderRoute: typeof AppLibraryLibraryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiagnosticsRoute: typeof AppDiagnosticsRoute
  AppDownloadsRoute: typeof AppDownloadsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppItemRatingKeyRoute: typeof AppItemRatingKeyRoute
  AppLibraryLibraryIdRoute: typeof AppLibraryLibraryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiagnosticsRoute: AppDiagnosticsRoute,
  AppDownloadsRoute: AppDownloadsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppItemRatingKeyRoute: AppItemRatingKeyRoute,
  AppLibraryLibraryIdRoute: AppLibraryLibraryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ServersRoute: ServersRoute,
  PlayRatingKeyRoute: PlayRatingKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
